# Generated by Django 4.1.7 on 2023-03-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_chemistry_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='video',
            field=models.FileField(upload_to='Media/'),
        ),
    ]
