# Generated by Django 4.1.7 on 2023-04-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_file_test_myfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='myfile',
            new_name='mfile',
        ),
    ]
