# Generated by Django 4.1.7 on 2023-04-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_myfile_test_mfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
