# Generated by Django 4.1.7 on 2023-04-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ouruser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('subject1', models.CharField(max_length=35, null=True)),
                ('subject2', models.CharField(max_length=35, null=True)),
                ('subject3', models.CharField(max_length=35, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
