# Generated by Django 4.1.7 on 2023-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_ouruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouruser',
            name='chem1',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='chem2',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='counter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='maths1',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='maths2',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='physics1',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='physics2',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
