# Generated by Django 4.1.7 on 2023-04-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_ouruser_chem1_ouruser_chem2_ouruser_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouruser',
            name='subject4',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='subject5',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='subject6',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
