# Generated by Django 4.1.7 on 2023-07-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_ouruser_subject4_ouruser_subject5_ouruser_subject6'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouruser',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='razorpay_payment_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='razorpay_signature',
            field=models.CharField(default='', max_length=500),
        ),
    ]
