# Generated by Django 4.1.7 on 2023-07-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ouruser_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='Media')),
            ],
        ),
    ]
