# Generated by Django 4.1.7 on 2023-07-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistry',
            name='chapter_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pdf',
            name='chapter_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
