# Generated by Django 4.1.7 on 2023-07-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_eleventh_video_delete_chemistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_title',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_title',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
