# Generated by Django 4.1.7 on 2023-07-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_pdf_chapter_name_alter_video_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleventh',
            name='status',
            field=models.CharField(default='Unpaid', max_length=20),
        ),
    ]
