# Generated by Django 4.1.7 on 2023-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_eleventh_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleventh',
            name='status',
        ),
        migrations.CreateModel(
            name='twelveth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.CharField(max_length=50)),
                ('chapter_name', models.CharField(max_length=500)),
                ('pdfs', models.ManyToManyField(blank=True, null=True, to='myapp.pdf')),
                ('videos', models.ManyToManyField(blank=True, null=True, to='myapp.video')),
            ],
        ),
    ]
