# Generated by Django 4.2.3 on 2023-08-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_ouruser_chem1_remove_ouruser_chem2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('order_id', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ouruser',
            name='userorder',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.order'),
        ),
    ]
