# Generated by Django 4.2.3 on 2023-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_order_ouruser_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flag',
            field=models.CharField(default='False', max_length=500),
        ),
    ]
