# Generated by Django 4.2.3 on 2023-08-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_ouruser_mycart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
