# Generated by Django 4.2.3 on 2023-08-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_cart_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='mycart',
        ),
    ]
