# Generated by Django 4.2.3 on 2023-08-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_cart_mycart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='order',
            name='chapter',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
