# Generated by Django 4.2.3 on 2023-08-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_order_title_order_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='razorpay_signature',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
