# Generated by Django 4.2.3 on 2023-08-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_status_short_video_pdf_status_video_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='Demo',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='Paid',
        ),
    ]
